
export const indianCities: string[] = [
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Bangalore, Karnataka",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Surat, Gujarat",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Kalyan-Dombivli, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu and Kashmir",
  "Aurangabad, Maharashtra",
  "Dhanbad, Jharkhand",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Allahabad, Uttar Pradesh",
  "Ranchi, Jharkhand",
  "Howrah, West Bengal",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Kota, Rajasthan",
  "Guwahati, Assam",
  "Chandigarh, Chandigarh",
  "Solapur, Maharashtra",
  "Hubli-Dharwad, Karnataka",
  "Bareilly, Uttar Pradesh",
  "Moradabad, Uttar Pradesh",
  "Mysore, Karnataka",
  "Gurgaon, Haryana",
  "Aligarh, Uttar Pradesh",
  "Jalandhar, Punjab",
  "Tiruchirappalli, Tamil Nadu",
  "Bhubaneswar, Odisha",
  "Salem, Tamil Nadu",
  "Warangal, Telangana",
  "Guntur, Andhra Pradesh",
  "Bhiwandi, Maharashtra",
  "Saharanpur, Uttar Pradesh",
  "Gorakhpur, Uttar Pradesh",
  "Bikaner, Rajasthan",
  "Amravati, Maharashtra",
  "Noida, Uttar Pradesh",
  "Jamshedpur, Jharkhand",
  "Bhilai, Chhattisgarh",
  "Cuttack, Odisha",
  "Firozabad, Uttar Pradesh",
  "Kochi, Kerala",
  "Nellore, Andhra Pradesh",
  "Bhavnagar, Gujarat",
  "Dehradun, Uttarakhand",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Rourkela, Odisha",
  "Nanded, Maharashtra",
  "Kolhapur, Maharashtra",
  "Ajmer, Rajasthan",
  "Gulbarga, Karnataka",
  "Jamnagar, Gujarat",
  "Ujjain, Madhya Pradesh",
  "Loni, Uttar Pradesh",
  "Siliguri, West Bengal",
  "Jhansi, Uttar Pradesh",
  "Ulhasnagar, Maharashtra",
  "Jammu, Jammu and Kashmir",
  "Sangli-Miraj & Kupwad, Maharashtra",
  "Mangalore, Karnataka",
  "Erode, Tamil Nadu",
  "Belgaum, Karnataka",
  "Ambattur, Tamil Nadu",
  "Tirunelveli, Tamil Nadu",
  "Malegaon, Maharashtra",
  "Gaya, Bihar",
  "Tiruppur, Tamil Nadu",
  "Davanagere, Karnataka",
  "Kozhikode, Kerala",
  "Akola, Maharashtra",
  "Kurnool, Andhra Pradesh",
  "Bokaro Steel City, Jharkhand",
  "Rajahmundry, Andhra Pradesh",
  "Ballari, Karnataka",
  "Agartala, Tripura",
  "Bhagalpur, Bihar",
  "Latur, Maharashtra",
  "Dhule, Maharashtra",
  "Korba, Chhattisgarh",
  "Bhilwara, Rajasthan",
  "Brahmapur, Odisha",
  "Muzaffarpur, Bihar",
  "Ahmednagar, Maharashtra",
  "Mathura, Uttar Pradesh",
  "Kollam, Kerala",
  "Avadi, Tamil Nadu",
  "Kadapa, Andhra Pradesh",
  "Kamarhati, West Bengal",
  "Sambalpur, Odisha",
  "Bilaspur, Chhattisgarh",
  "Shahjahanpur, Uttar Pradesh",
  "Satara, Maharashtra",
  "Thrissur, Kerala",
  "Alwar, Rajasthan",
  "Kakinada, Andhra Pradesh",
  "Panipat, Haryana",
  "Darbhanga, Bihar",
  "Panvel, Maharashtra",
  "Karimnagar, Telangana",
  "Aizawl, Mizoram",
  "Puducherry, Puducherry",
  "Gandhinagar, Gujarat",
  "Shimla, Himachal Pradesh",
  "Goa, Goa"
];
